// // TODO: Tianqi — replace this entire file with your DonorPanel implementation
// // export default function DonorPanel() {
// //   return (
// //     <div className="flex items-center justify-center h-64 text-gray-400">
// //       <p>DonorPanel — Tianqi, replace this file</p>
// //     </div>
// //   );
// // }

// import React, { useState, useEffect } from 'react';
// import { sendPayment, getBalance } from '../xrpl/client';
// import { createEscrow, finishEscrow } from '../xrpl/escrow';
// import { MILESTONES } from '../data/milestones';
// import { WALLETS } from '../data/wallets'; // Paing defined wallets

// export default function DonorPanel() {
//   const [balance, setBalance] = useState("0");
//   const [status, setStatus] = useState("");
//   const [loading, setLoading] = useState(false);

//   // 1. automatically refresh balance
//   useEffect(() => {
//     const fetchBalance = async () => {
//       const b = await getBalance(WALLETS.donor.address);
//       setBalance(b);
//     };
//     fetchBalance();
//     // refresh every 10 seconds, or manually after a transaction
//     const timer = setInterval(fetchBalance, 10000);
//     return () => clearInterval(timer);
//   }, []);

//   // 2. Fund all milestones
//   const handleFundAll = async () => {
//     setLoading(true);
//     setStatus("Preparing donation...");

//     try {
//       // Step A: send total amount to fund account (Fund Account)
//       // Note: Paing's sendPayment receives object parameters
//       setStatus("Step 1: Sending funds to project account...");
//       await sendPayment({
//         wallet: WALLETS.donor,        // donor wallet
//         destination: wallets.fund.address, // fund account address
//         amount: "225"                 // total amount
//       });

//       // Step B: create one escrow for each milestone (3 loops)
//       for (let i = 0; i < MILESTONES.length; i++) {
//         const m = MILESTONES[i];
//         setStatus(`Step 2: Creating Escrow for ${m.title} (${i + 1}/3)...`);
        
//         // call Paing's createEscrow
//         await createEscrow({
//           fromWallet: WALLETS.fund,    // lock funds from fund account
//           destination: WALLETS.beneficiary.address, // beneficiary address
//           amount: m.amount,            // current milestone amount
//           condition: m.conditionHex,   // generated by Angelina's condition.js
//           cancelAfterDays: 30         // 30 days
//         });
//       }

//       setStatus("Success! All 3 milestones funded and locked on-chain.");
//     } catch (error) {
//       console.error("Donation failed:", error);
//       setStatus("Error: " + error.message);
//     } finally {
//       setLoading(false);
//     }
//   };

//   return (
//     <div className="donor-panel p-4 border rounded-xl shadow">
//         {/* TODO: your UI code... */}
//       <div className="mb-4">
//         <p className="text-gray-500">Your Balance</p>
//         <h3 className="text-2xl font-bold">{balance} XRP</h3>
//       </div>

//       <button 
//         onClick={handleFundAll}
//         disabled={loading}
//         className="w-full bg-blue-600 text-white py-3 rounded-lg font-bold"
//       >
//         {loading ? "Processing..." : "Fund All Milestones (225 XRP)"}
//       </button>

//       {status && (
//         <div className="mt-4 p-3 bg-blue-50 text-blue-700 text-sm rounded">
//           {status}
//         </div>
//       )}
//     </div>
//   );
// }


import React, { useState, useEffect } from 'react';
import { Wallet, Gift, ExternalLink, CheckCircle2, Loader2, Award } from 'lucide-react';
import { sendPayment, getBalance } from '../xrpl/client';
import { createEscrow } from '../xrpl/escrow';
import { generateCondition } from '../xrpl/condition';
import { TOTAL_FUNDING_GOAL } from '../data/milestones';
import { WALLETS } from '../data/wallets';

export default function DonorPanel({ milestones, wallets, updateMilestoneEscrow, refreshBalances }) {
  const [balance, setBalance] = useState("---");
  const [amount, setAmount] = useState(TOTAL_FUNDING_GOAL);
  const [status, setStatus] = useState("");
  const [progress, setProgress] = useState(0); // from 0 to 3
  const [loading, setLoading] = useState(false);
  const [nfts, setNfts] = useState([]); // assume from nft.js

  // automatically refresh balance
  useEffect(() => {
    const fetchBalance = async () => {
      const b = await getBalance(WALLETS.donor.address);
      setBalance(b);
    };
    fetchBalance();
    const timer = setInterval(fetchBalance, 12000);
    return () => clearInterval(timer);
  }, []);

  const handleFundAll = async () => {
    setLoading(true);
    setProgress(0);
    try {
      // Step 1: Send total XRP from donor to fund account
      setStatus("Step 1: Sending total payment to Fund Account...");
      await sendPayment({
        wallet: wallets.donor,
        destination: wallets.fund.address,
        amount: amount.toString()
      });

      // Step 2: Create one escrow per milestone with its own crypto-condition
      for (let i = 0; i < milestones.length; i++) {
        const m = milestones[i];
        setStatus(`Step 2: Creating Escrow for ${m.title}... (${i + 1}/${milestones.length})`);

        // Generate a unique condition/fulfillment pair for this milestone
        const { condition, fulfillment } = await generateCondition();

        const { result, sequence } = await createEscrow({
          fromWallet: wallets.fund,
          destination: wallets.beneficiary.address,
          amount: m.xrpAmount,
          condition,
        });

        // Extract tx hash from result
        const escrowTxHash = result?.result?.tx_json?.hash || null;

        // Update app state so other panels can see this milestone is funded
        updateMilestoneEscrow(m.id, {
          escrowSequence: sequence,
          condition,
          fulfillment,
          escrowTxHash,
        });

        setProgress(i + 1);
      }

      refreshBalances();
      setStatus("Done! All milestones funded and locked on-chain.");
    } catch (err) {
      setStatus("Error: " + err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6 max-w-2xl mx-auto p-6">
      {/* 1. wallet status card */}
      <div className="bg-gradient-to-br from-blue-600 to-indigo-700 rounded-2xl p-6 text-white shadow-lg">
        <div className="flex justify-between items-start">
          <div>
            <p className="text-blue-100 text-sm font-medium flex items-center gap-2">
              <Wallet size={16} /> my donation wallet
            </p>
            <h2 className="text-3xl font-bold mt-1">{balance} <span className="text-lg">XRP</span></h2>
            <code className="text-[10px] opacity-70 mt-2 block break-all">{WALLETS.donor.address}</code>
          </div>
          <div className="bg-white/20 p-3 rounded-xl backdrop-blur-md">
            <Gift size={24} />
          </div>
        </div>
      </div>

      {/* 2. donation operation area */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm">
        <label className="block text-sm font-semibold text-slate-700 mb-3 text-center">
           select donation amount (funding all milestones requires {TOTAL_FUNDING_GOAL} XRP)
        </label>
        <div className="flex gap-4 mb-6">
          <input 
            type="number"
            value={amount}
            onChange={(e) => setAmount(e.target.value)}
            className="flex-1 px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none font-bold text-lg"
          />
          <button 
            onClick={() => setAmount(TOTAL_FUNDING_GOAL)}
            className="px-4 py-2 text-sm text-blue-600 font-medium hover:bg-blue-50 rounded-lg transition-colors"
          >
            reset default
          </button>
        </div>

        <button 
          onClick={handleFundAll}
          disabled={loading}
          className={`w-full py-4 rounded-xl font-bold text-lg flex justify-center items-center gap-3 transition-all ${
            loading ? 'bg-slate-100 text-slate-400' : 'bg-blue-600 text-white hover:bg-blue-700 shadow-md active:scale-[0.98]'
          }`}
        >
          {loading ? <Loader2 className="animate-spin" /> : <CheckCircle2 />}
          {loading ? `Funding... ${progress}/3` : "fund all milestones (Fund All)"}
        </button>

        {status && (
          <div className={`mt-4 p-3 rounded-lg text-sm font-medium text-center ${status.includes('❌') ? 'bg-red-50 text-red-600' : 'bg-blue-50 text-blue-700'}`}>
            {status}
          </div>
        )}
      </div>

      {/* 3. NFT achievement wall (Impact Portfolio) */}
      <div className="pt-4">
        <h3 className="text-lg font-bold text-slate-800 flex items-center gap-2 mb-4">
          <Award className="text-amber-500" /> my impact achievement (NFTs)
        </h3>
        {nfts.length === 0 ? (
          <div className="border-2 border-dashed border-slate-200 rounded-2xl p-10 text-center text-slate-400">
            <p>no achievement yet. you will receive the on-chain receipt NFT after donation</p>
          </div>
        ) : (
          <div className="grid grid-cols-2 gap-4">
            {/* NFT Card example - use nfts.map to render */}
            <div className="bg-white border border-slate-200 p-4 rounded-xl shadow-sm hover:shadow-md transition-shadow">
              <div className="aspect-square bg-slate-100 rounded-lg mb-3 flex items-center justify-center">
                🖼️
              </div>
              <p className="font-bold text-sm">Donation Receipt #1</p>
              <p className="text-xs text-slate-500">Amount: 100 XRP</p>
              <a href="#" className="mt-2 text-[10px] text-blue-600 flex items-center gap-1">
                View on Explorer <ExternalLink size={10} />
              </a>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
