// TODO: Tianqi — replace this entire file with your DonorPanel implementation
// export default function DonorPanel() {
//   return (
//     <div className="flex items-center justify-center h-64 text-gray-400">
//       <p>DonorPanel — Tianqi, replace this file</p>
//     </div>
//   );
// }

import React, { useState, useEffect } from 'react';
import { sendPayment, getBalance } from '../xrpl/client';
import { createEscrow, finishEscrow } from '../xrpl/escrow';
import { MILESTONES } from '../data/milestones';
import { WALLETS } from '../data/wallets'; // Paing defined wallets

export default function DonorPanel() {
  const [balance, setBalance] = useState("0");
  const [status, setStatus] = useState("");
  const [loading, setLoading] = useState(false);

  // 1. automatically refresh balance
  useEffect(() => {
    const fetchBalance = async () => {
      const b = await getBalance(WALLETS.donor.address);
      setBalance(b);
    };
    fetchBalance();
    // refresh every 10 seconds, or manually after a transaction
    const timer = setInterval(fetchBalance, 10000);
    return () => clearInterval(timer);
  }, []);

  // 2. Fund all milestones
  const handleFundAll = async () => {
    setLoading(true);
    setStatus("Preparing donation...");

    try {
      // Step A: send total amount to fund account (Fund Account)
      // Note: Paing's sendPayment receives object parameters
      setStatus("Step 1: Sending funds to project account...");
      await sendPayment({
        wallet: WALLETS.donor,        // donor wallet
        destination: wallets.fund.address, // fund account address
        amount: "225"                 // total amount
      });

      // Step B: create one escrow for each milestone (3 loops)
      for (let i = 0; i < MILESTONES.length; i++) {
        const m = MILESTONES[i];
        setStatus(`Step 2: Creating Escrow for ${m.title} (${i + 1}/3)...`);
        
        // call Paing's createEscrow
        await createEscrow({
          fromWallet: WALLETS.fund,    // lock funds from fund account
          destination: WALLETS.beneficiary.address, // beneficiary address
          amount: m.amount,            // current milestone amount
          condition: m.conditionHex,   // generated by Angelina's condition.js
          cancelAfterDays: 30         // 30 days
        });
      }

      setStatus("Success! All 3 milestones funded and locked on-chain.");
    } catch (error) {
      console.error("Donation failed:", error);
      setStatus("Error: " + error.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="donor-panel p-4 border rounded-xl shadow">
        {/* TODO: your UI code... */}
      <div className="mb-4">
        <p className="text-gray-500">Your Balance</p>
        <h3 className="text-2xl font-bold">{balance} XRP</h3>
      </div>

      <button 
        onClick={handleFundAll}
        disabled={loading}
        className="w-full bg-blue-600 text-white py-3 rounded-lg font-bold"
      >
        {loading ? "Processing..." : "Fund All Milestones (225 XRP)"}
      </button>

      {status && (
        <div className="mt-4 p-3 bg-blue-50 text-blue-700 text-sm rounded">
          {status}
        </div>
      )}
    </div>
  );
}